{% set version = "1.1.0" %}

package:
  name: cmos_noise_map
  version: {{ 1.1.0 }}

source:
  path: ../

build:
  noarch: python
  number: 0
  script: python3 -m pip install --no-deps --ignore-installed .

requirements:
  run:
    - python
    - pip
    - python
    - astropy
    - numpy
    - scipy
    - glob2
    - pytest
    - scikit-learn
    - click
    - matplotlib
    - pandas
    - sphinx